# Generated by Django 3.2.3 on 2021-06-23 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to=settings.AUTH_USER_MODEL),
        ),
    ]
