# Generated by Django 3.2.3 on 2021-06-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_phoneotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='stylist_id',
            field=models.IntegerField(auto_created=True, default=1, unique=True),
        ),
    ]
