# Generated by Django 3.2.3 on 2021-07-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_stylist_stylist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='number',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
