# Generated by Django 3.2.3 on 2021-07-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_phoneotp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='email_is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='phone_is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
