# Generated by Django 3.2.3 on 2021-07-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210713_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
