# Generated by Django 3.2.3 on 2021-07-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210713_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
